# Usage:
#   docker-compose -f docker-compose-zalenium.yml up --force-recreate
version: '2.1'

services:
  #--------------#
  zalenium:
    image: "dosel/zalenium"
    container_name: zalenium
    hostname: zalenium
    tty: true
    volumes:
    - ./target/videos:/home/seluser/videos
#    Zalenium uses docker to scale on-demand, therefore we need to give it the docker.sock full access, this is known as "Docker alongside docker".
#    Currently does not work on Windows
#    export COMPOSE_CONVERT_WINDOWS_PATHS=1 (Bash)
    - //var/run/docker.sock:/var/run/docker.sock
    ports:
    - 4444:4444
    command: >
      start --desiredContainers 2
            --maxDockerSeleniumContainers 8
            --screenWidth 800 --screenHeight 600
            --timeZone "Europe/Berlin"
            --videoRecordingEnabled true
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --startTunnel false
    environment:
    - HOST_UID
    - HOST_GID
    - SAUCE_USERNAME
    - SAUCE_ACCESS_KEY
    - BROWSER_STACK_USER
    - BROWSER_STACK_KEY
    - TESTINGBOT_KEY
    - TESTINGBOT_SECRET

  mock:
    image: elgalu/google_adwords_mock
    depends_on:
    - zalenium
    ports:
    - 8080:8080
    tty: true
    environment:
    - MOCK_SERVER_PORT=8080